"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['folderCreater.py']
DATA_FILES = []
OPTIONS = {'iconfile': 'D:\\Dulwich\\Further Maths\\programs\\D1\\icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
